require 'rake'
require 'rspec/core/rake_task'
require'yaml'

properties = YAML.load_file('spec_hosts.yml')
 
desc "Run serverspec to all hosts"
task :spec => 'serverspec:all'
 
class ServerspecTask < RSpec::Core::RakeTask
 
  attr_accessor :target
 
  def spec_command
    cmd = super
    "env TARGET_HOST=#{target} #{cmd}"
  end
 
end
 
namespace :serverspec do
  task :all => properties.keys.map {|key| 'serverspec:' + key }
  properties.keys.each do |key|
    desc "Run serverspec to #{key}"
    ServerspecTask.new(key) do |t|
      t.target = key
      t.pattern = 'spec/{' + properties[key][:roles].join(',') + '}/*_spec.rb'
    end
  end
end
